apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgeagent-data-azurefile
  namespace: pv-iotedged
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 100Mi
